services:
  - type: web
    name: dsa-mastery-sheet
    env: node
    region: oregon
    buildCommand: npm install --prefix server && npm install --prefix client && npm run build:export --prefix client
    startCommand: npm start --prefix server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
